config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :authors
    resources :authors_books
    resources :books
    resources :books_tags
    resources :tags

    root to: "users#index"
  end

  resources :tags
  devise_for :users
  resources :authors
  resources :books
  root "books#index"

  namespace :api do
    namespace :v1 do
      resources :books
    end
  end
end

app/models/book.rb
class Book < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_and_belongs_to_many :authors
  has_and_belongs_to_many :tags

  def author_names
    comma_separated_list(:authors)
  end

  def tag_names
    comma_separated_list(:tags)
  end

  def comma_separated_list(association_name)
    send(association_name).map(&:name).join(', ')
  end
end

app/controllers/admin/books_controller.rb
module Admin
  class BooksController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Book.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Book.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/api/v1/books_controller.rb
class API::V1::BooksController < API::V1::APIController
  skip_before_action :authenticate_user!

  def index
    @books = Book.all

    render json: @books
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :set_options, only: [:new, :edit, :update, :create]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    respond_to do |format|
      Book.transaction do
        @book = Book.new(book_params)

        if @book.save
          format.html { redirect_to @book, notice: 'Book was successfully created.' }
          format.json { render :show, status: :created, location: @book }
        else
          format.html { render :new }
          format.json { render json: @book.errors, status: :unprocessable_entity }
          raise ActiveRecord::Rollback unless @book.valid?
        end
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      Book.transaction do
        if @book.update(book_params)
          format.html { redirect_to @book, notice: 'Book was successfully updated.' }
          format.json { render :show, status: :ok, location: @book }
        else
          format.html { render :edit }
          format.json { render json: @book.errors, status: :unprocessable_entity }
          raise ActiveRecord::Rollback unless @book.valid?
        end
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    def set_options
      @author_options = Author.all.collect { |a| [a.name, a.id] }
      @tag_options = Tag.all.collect { |a| [a.name, a.id] }
    end

    def create_authors_from_params(original_params)
      BookParamsWithAuthorStrings.new(original_params).process
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      create_authors_from_params(params.require(:book).permit(:name, author_ids: [], tag_ids: []))
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_for(book) do |f| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :author_ids, 'Authors' %>
    <%= f.select(:author_ids, @author_options, {}, { multiple: true }) %>
  </div>

  <div class="field">
    <%= f.label :tag_ids, 'Tags' %>
    <%= f.select(:tag_ids, @tag_options, {}, { multiple: true }) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.name %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @book.name %>
</p>

<p>
  <strong>Author(s):</strong>
  <%= @book.author_names %>
</p>

<p>
  <strong>Tag(s):</strong>
  <%= @book.tag_names %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>